// <auto-generated />
using Final_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251212020815_SeedMoviesAndRatings")]
    partial class SeedMoviesAndRatings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Final_Project.Models.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("MovieID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            PosterUrl = "/img/movies/inception.jpg",
                            ReleaseYear = 2010,
                            Summary = "A skilled thief enters dreams to steal secrets, but his toughest job is planting an idea instead.",
                            Title = "Inception"
                        },
                        new
                        {
                            MovieID = 2,
                            PosterUrl = "/img/movies/interstellar.jpg",
                            ReleaseYear = 2014,
                            Summary = "Explorers travel through a wormhole in space to save humanity from a dying Earth.",
                            Title = "Interstellar"
                        },
                        new
                        {
                            MovieID = 3,
                            PosterUrl = "/img/movies/matrix.jpg",
                            ReleaseYear = 1999,
                            Summary = "A hacker learns that reality is a simulation and joins a rebellion against its controllers.",
                            Title = "The Matrix"
                        },
                        new
                        {
                            MovieID = 4,
                            PosterUrl = "/img/movies/bladerunner2049.jpg",
                            ReleaseYear = 2017,
                            Summary = "A young blade runner uncovers a secret that could plunge society into chaos.",
                            Title = "Blade Runner 2049"
                        },
                        new
                        {
                            MovieID = 5,
                            PosterUrl = "/img/movies/darkknight.jpg",
                            ReleaseYear = 2008,
                            Summary = "Batman faces the Joker, a criminal mastermind bent on breaking Gotham’s spirit.",
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            MovieID = 6,
                            PosterUrl = "/img/movies/arrival.jpg",
                            ReleaseYear = 2016,
                            Summary = "A linguist races to communicate with alien visitors before global conflict erupts.",
                            Title = "Arrival"
                        },
                        new
                        {
                            MovieID = 7,
                            PosterUrl = "/img/movies/dune.jpg",
                            ReleaseYear = 2021,
                            Summary = "A noble family becomes embroiled in a war for control over the galaxy’s most valuable resource.",
                            Title = "Dune"
                        },
                        new
                        {
                            MovieID = 8,
                            PosterUrl = "/img/movies/eeaao.jpg",
                            ReleaseYear = 2022,
                            Summary = "An overwhelmed woman explores parallel universes to save existence itself.",
                            Title = "Everything Everywhere All at Once"
                        },
                        new
                        {
                            MovieID = 9,
                            PosterUrl = "/img/movies/prestige.jpg",
                            ReleaseYear = 2006,
                            Summary = "Two rival magicians obsessively compete to create the ultimate illusion.",
                            Title = "The Prestige"
                        },
                        new
                        {
                            MovieID = 10,
                            PosterUrl = "/img/movies/exmachina.jpg",
                            ReleaseYear = 2014,
                            Summary = "A programmer evaluates an AI with unsettlingly human traits.",
                            Title = "Ex Machina"
                        },
                        new
                        {
                            MovieID = 11,
                            PosterUrl = "/img/movies/parasite.jpg",
                            ReleaseYear = 2019,
                            Summary = "A poor family schemes to infiltrate a wealthy household with unexpected consequences.",
                            Title = "Parasite"
                        },
                        new
                        {
                            MovieID = 12,
                            PosterUrl = "/img/movies/madmax.jpg",
                            ReleaseYear = 2015,
                            Summary = "Survivors flee across the wasteland in a relentless chase for freedom.",
                            Title = "Mad Max: Fury Road"
                        },
                        new
                        {
                            MovieID = 13,
                            PosterUrl = "/img/movies/whiplash.jpg",
                            ReleaseYear = 2014,
                            Summary = "A young drummer pushes himself to the brink under a ruthless instructor.",
                            Title = "Whiplash"
                        },
                        new
                        {
                            MovieID = 14,
                            PosterUrl = "/img/movies/her.jpg",
                            ReleaseYear = 2013,
                            Summary = "A lonely writer forms an emotional bond with an advanced operating system.",
                            Title = "Her"
                        },
                        new
                        {
                            MovieID = 15,
                            PosterUrl = "/img/movies/grandbudapest.jpg",
                            ReleaseYear = 2014,
                            Summary = "A hotel concierge becomes entangled in theft, war, and loyalty.",
                            Title = "The Grand Budapest Hotel"
                        },
                        new
                        {
                            MovieID = 16,
                            PosterUrl = "/img/movies/nocountry.jpg",
                            ReleaseYear = 2007,
                            Summary = "A hunter stumbles upon a drug deal gone wrong and unleashes a relentless killer.",
                            Title = "No Country for Old Men"
                        },
                        new
                        {
                            MovieID = 17,
                            PosterUrl = "/img/movies/fightclub.jpg",
                            ReleaseYear = 1999,
                            Summary = "An insomniac forms an underground fight club that spirals out of control.",
                            Title = "Fight Club"
                        },
                        new
                        {
                            MovieID = 18,
                            PosterUrl = "/img/movies/socialnetwork.jpg",
                            ReleaseYear = 2010,
                            Summary = "The founding of a social media empire leads to betrayal and lawsuits.",
                            Title = "The Social Network"
                        },
                        new
                        {
                            MovieID = 19,
                            PosterUrl = "/img/movies/shutterisland.jpg",
                            ReleaseYear = 2010,
                            Summary = "A U.S. Marshal investigates a disappearance at a mysterious asylum.",
                            Title = "Shutter Island"
                        },
                        new
                        {
                            MovieID = 20,
                            PosterUrl = "/img/movies/truman.jpg",
                            ReleaseYear = 1998,
                            Summary = "A man slowly realizes his entire life is a television show.",
                            Title = "The Truman Show"
                        },
                        new
                        {
                            MovieID = 21,
                            PosterUrl = "/img/movies/joker.jpg",
                            ReleaseYear = 2019,
                            Summary = "A failed comedian descends into madness and chaos.",
                            Title = "Joker"
                        },
                        new
                        {
                            MovieID = 22,
                            PosterUrl = "/img/movies/getout.jpg",
                            ReleaseYear = 2017,
                            Summary = "A weekend visit uncovers disturbing secrets beneath polite smiles.",
                            Title = "Get Out"
                        },
                        new
                        {
                            MovieID = 23,
                            PosterUrl = "/img/movies/lighthouse.jpg",
                            ReleaseYear = 2019,
                            Summary = "Two lighthouse keepers descend into madness on a remote island.",
                            Title = "The Lighthouse"
                        },
                        new
                        {
                            MovieID = 24,
                            PosterUrl = "/img/movies/lalaland.jpg",
                            ReleaseYear = 2016,
                            Summary = "An aspiring actress and a jazz musician chase dreams in Los Angeles.",
                            Title = "La La Land"
                        },
                        new
                        {
                            MovieID = 25,
                            PosterUrl = "/img/movies/shawshank.jpg",
                            ReleaseYear = 1994,
                            Summary = "A wrongfully imprisoned man forms a life-changing friendship behind bars.",
                            Title = "The Shawshank Redemption"
                        });
                });

            modelBuilder.Entity("Final_Project.Models.Rating", b =>
                {
                    b.Property<int>("RatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("RatingID");

                    b.HasIndex("MovieID");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            RatingID = 1,
                            MovieID = 1,
                            ReviewText = "Mind-bending and brilliant.",
                            Score = 5
                        },
                        new
                        {
                            RatingID = 2,
                            MovieID = 1,
                            ReviewText = "Complex but rewarding.",
                            Score = 4
                        },
                        new
                        {
                            RatingID = 3,
                            MovieID = 2,
                            ReviewText = "Visually stunning and emotional.",
                            Score = 5
                        },
                        new
                        {
                            RatingID = 4,
                            MovieID = 2,
                            ReviewText = "An unforgettable journey.",
                            Score = 5
                        },
                        new
                        {
                            RatingID = 5,
                            MovieID = 3,
                            ReviewText = "Revolutionary sci-fi.",
                            Score = 5
                        },
                        new
                        {
                            RatingID = 6,
                            MovieID = 3,
                            ReviewText = "Still holds up today.",
                            Score = 4
                        },
                        new
                        {
                            RatingID = 7,
                            MovieID = 5,
                            ReviewText = "Best superhero movie ever.",
                            Score = 5
                        },
                        new
                        {
                            RatingID = 8,
                            MovieID = 5,
                            ReviewText = "Heath Ledger was incredible.",
                            Score = 4
                        },
                        new
                        {
                            RatingID = 9,
                            MovieID = 8,
                            ReviewText = "Absolutely wild and emotional.",
                            Score = 5
                        },
                        new
                        {
                            RatingID = 10,
                            MovieID = 8,
                            ReviewText = "Strange but beautiful.",
                            Score = 4
                        },
                        new
                        {
                            RatingID = 11,
                            MovieID = 11,
                            ReviewText = "Sharp, funny, and unsettling.",
                            Score = 5
                        },
                        new
                        {
                            RatingID = 12,
                            MovieID = 11,
                            ReviewText = "Deserved every award.",
                            Score = 5
                        },
                        new
                        {
                            RatingID = 13,
                            MovieID = 17,
                            ReviewText = "Stylish and provocative.",
                            Score = 4
                        },
                        new
                        {
                            RatingID = 14,
                            MovieID = 17,
                            ReviewText = "A bit overrated but interesting.",
                            Score = 3
                        },
                        new
                        {
                            RatingID = 15,
                            MovieID = 25,
                            ReviewText = "Timeless and inspiring.",
                            Score = 5
                        });
                });

            modelBuilder.Entity("Final_Project.Models.Rating", b =>
                {
                    b.HasOne("Final_Project.Models.Movie", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Final_Project.Models.Movie", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
