// <auto-generated />
using Final_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251212005521_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Final_Project.Models.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("MovieID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            PosterUrl = "https://via.placeholder.com/240x360?text=EGGY+1",
                            ReleaseYear = 2016,
                            Summary = "A washed-up chef uncovers an underground egg-rating ring.",
                            Title = "EGGY: The First Crack"
                        },
                        new
                        {
                            MovieID = 2,
                            PosterUrl = "https://via.placeholder.com/240x360?text=Yolk+Runner",
                            ReleaseYear = 2017,
                            Summary = "A courier smuggles illegal breakfasts across a neon city.",
                            Title = "Yolk Runner"
                        },
                        new
                        {
                            MovieID = 3,
                            PosterUrl = "https://via.placeholder.com/240x360?text=Shellshock",
                            ReleaseYear = 2018,
                            Summary = "A drummer hears messages hidden in cracked shells.",
                            Title = "Shellshock"
                        },
                        new
                        {
                            MovieID = 25,
                            PosterUrl = "https://via.placeholder.com/240x360?text=Cracked+Horizons",
                            ReleaseYear = 1999,
                            Summary = "A sci-fi expedition finds a planet where memory is edible.",
                            Title = "Cracked Horizons"
                        });
                });

            modelBuilder.Entity("Final_Project.Models.Rating", b =>
                {
                    b.Property<int>("RatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("RatingID");

                    b.HasIndex("MovieID");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            RatingID = 1,
                            MovieID = 1,
                            ReviewText = "Peak EGGY cinema.",
                            Score = 5
                        },
                        new
                        {
                            RatingID = 2,
                            MovieID = 1,
                            ReviewText = "Better than expected.",
                            Score = 4
                        },
                        new
                        {
                            RatingID = 3,
                            MovieID = 2,
                            ReviewText = "Cool vibe, thin story.",
                            Score = 3
                        },
                        new
                        {
                            RatingID = 4,
                            MovieID = 3,
                            ReviewText = "Didn’t land for me.",
                            Score = 2
                        });
                });

            modelBuilder.Entity("Final_Project.Models.Rating", b =>
                {
                    b.HasOne("Final_Project.Models.Movie", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Final_Project.Models.Movie", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
